export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DEET_REQUEST = 'PRODUCT_DEET_REQUEST'
export const PRODUCT_DEET_SUCCESS = 'PRODUCT_DEET_SUCCESS'
export const PRODUCT_DEET_FAIL = 'PRODUCT_DEET_FAIL'